### Import thư viện

In [1]:
import torch
import numpy as np

### Khởi tạo tensor

In [2]:
data = [[1, 2],[3, 4]]
x_data = torch.tensor(data)
x_data

tensor([[1, 2],
        [3, 4]])

In [3]:
x_data2 = [[1, 2, 3], [3, 2, 1], [3, 3, 3]]
x_data2 = torch.tensor(x_data2)
x_data2

tensor([[1, 2, 3],
        [3, 2, 1],
        [3, 3, 3]])

In [4]:
np_array = np.array(data)
np_array

array([[1, 2],
       [3, 4]])

In [5]:
x_np = torch.from_numpy(np_array)

print(f"Numpy np_array value: \n {np_array} \n")
print(f"Tensor x_np value: \n {x_np} \n")



Numpy np_array value: 
 [[1 2]
 [3 4]] 

Tensor x_np value: 
 tensor([[1, 2],
        [3, 4]], dtype=torch.int32) 



In [6]:
np.multiply(np_array, 2, out=np_array)

print(f"Numpy np_array after * 2 operation: \n {np_array} \n")
print(f"Tensor x_np value after modifying numpy array: \n {x_np} \n")

Numpy np_array after * 2 operation: 
 [[2 4]
 [6 8]] 

Tensor x_np value after modifying numpy array: 
 tensor([[2, 4],
        [6, 8]], dtype=torch.int32) 



In [7]:
x_ones = torch.ones_like(x_data) # retains the properties of x_data
print(f"Ones Tensor: \n {x_ones} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 



In [10]:
x_rand = torch.rand_like(x_data, dtype=torch.float) # overrides the datatype of x_data
print(f"Random Tensor: \n {x_rand} \n")

Random Tensor: 
 tensor([[0.8004, 0.2889],
        [0.0677, 0.2413]]) 



In [11]:
shape = (2,3)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.2960, 0.4291, 0.1977],
        [0.2695, 0.1706, 0.6601]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


### Các thuộc tính của tensor


In [12]:
tensor = torch.rand(3,4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


### Các thao tác trên tensor
https://pytorch.org/docs/stable/torch.html

In [13]:
# We move our tensor to the GPU if available
if torch.cuda.is_available():
  tensor = tensor.to('cuda')

In [14]:
torch.cuda.is_available()

False

In [15]:
torch.is_tensor(tensor)

True

### Lập chỉ mục và cắt lát giống như numpy tiêu chuẩn

In [23]:
tensor = torch.rand(4, 4)
tensor

tensor([[0.4926, 0.3257, 0.7036, 0.4439],
        [0.4451, 0.9636, 0.3484, 0.2659],
        [0.2447, 0.2217, 0.5737, 0.6850],
        [0.9714, 0.3572, 0.1329, 0.6148]])

In [25]:
print('First row: ',tensor[0])

First row:  tensor([0.4926, 0.3257, 0.7036, 0.4439])


In [26]:
print('First column: ', tensor[:, 0])

First column:  tensor([0.4926, 0.4451, 0.2447, 0.9714])


In [30]:
print('Last column:', tensor[..., -1])

Last column: tensor([0.4439, 0.2659, 0.6850, 0.6148])


In [31]:
tensor[:,1] = 0
print(tensor)

tensor([[0.4926, 0.0000, 0.7036, 0.4439],
        [0.4451, 0.0000, 0.3484, 0.2659],
        [0.2447, 0.0000, 0.5737, 0.6850],
        [0.9714, 0.0000, 0.1329, 0.6148]])


### Kết nối các tensor

In [35]:
tensor = torch.ones(3, 3)
tensor2 = torch.zeros(3, 3)
tensor, tensor2

(tensor([[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]),
 tensor([[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]))

In [37]:
t1 = torch.cat([tensor, tensor2], dim=0)
print(t1)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [40]:
t1.T

tensor([[1., 1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0., 0.]])

### Phép tính số học

In [41]:
# This computes the matrix multiplication between two tensors. y1, y2, y3 will have the same value
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)

y3 = torch.rand_like(tensor)
torch.matmul(tensor, tensor.T, out=y3)
print(y3)

tensor([[3., 3., 3.],
        [3., 3., 3.],
        [3., 3., 3.]])


In [43]:
tensor

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [45]:
# This computes the element-wise product. z1, z2, z3 will have the same value
z1 = tensor * tensor
z2 = tensor.mul(tensor)

z3 = torch.rand_like(tensor)
torch.mul(tensor, z3, out=z3)

tensor([[0.5416, 0.0950, 0.7828],
        [0.9941, 0.3459, 0.6365],
        [0.1920, 0.6340, 0.0450]])

In [46]:
z3

tensor([[0.5416, 0.0950, 0.7828],
        [0.9941, 0.3459, 0.6365],
        [0.1920, 0.6340, 0.0450]])

### Tensor to NumPy array

In [47]:
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


In [48]:
t.add_(1)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


### NumPy array to tensor

In [49]:
n = np.ones(5)
t = torch.from_numpy(n)

In [50]:
np.add(n, 1, out=n)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]
